### ISSUE TITLE
edge and IE on touch devices

### ISSUE THREAD

**Issue by mayklEm** [malihu/malihu-custom-scrollbar-plugin#353]
http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html
seems like there is issue with Microsoft Edge and IE. Scrolling on touch screens (talking about laptop, not tablet) doesn't work at all even on your demo.
Mouse scrolling works without problems.

**Comment by sava999** [comment]
I have same issue. Scrolling on touch doesn't work in IE. Tested on Asus Transformer & IE 11.

Is there any solution for this?

**Comment by malihu** [comment]
I'll investigate this further. In the meantime, please check the [previous version 3.0.8](https://github.com/malihu/malihu-custom-scrollbar-plugin/releases/tag/3.0.8) and let me know if it does work (replace both .js and .css files).

**Comment by sava999** [comment]
Hi,

Thank you for quick response.

I tested 3.0.8 and it is not working in IE also. But it looks like 3.0.5 is working.

BTW, I was testing on your "simple_example_all_params" example.

**Comment by mayklEm** [comment]
@sava999  yes I confirm that scroll works fine with 3.0.5 except: didn't you face a problem with anchors? If I touch the section where anchor tag is, scroll the section and release fro the same area where anchor is it will trigger a click event on release

**Comment by sava999** [comment]
@mayklEm sorry, my code don't have anchors so I didn't notice that issue.

But, after testing in more details I can confirm that 3.0.5 is also not working as expected. 3.0.5 is not working for select tag. If you touch, pull up or down, after finger release option that you first touched will be selected.

**Comment by sava999** [comment]
I can see that version from master is also not working for select tag in IE.

**Comment by malihu** [comment]
OK did some tests and found the issue. I'll push the fix immediately on the upcoming version (3.1.0) which I'll release within the next 3 days.

**Comment by malihu** [comment]
This should be fixed in version 3.1.0. Get latest version (replace .js and .css) and let me know :)

**Comment by mayklEm** [comment]
Unfortunately still doesn't work :/. As an example you can see the demo from my initial comment

**Comment by malihu** [comment]
Any chance you're seeing a cached page? Can you (re)download the plugin and check the demo locally?

**Comment by sava999** [comment]
It is not working for me also.

**Comment by malihu** [comment]
It doesn't scroll at all? In either IE or Edge?

**Comment by malihu** [comment]
Also is the scrollbar draggable? Can you scroll content by touch-dragging the scrollbar?

**Comment by sava999** [comment]
On Edge when you touch on container which should be scroll able and pull up or down complete page scrolls up or down.

When you use scroll bar on the right side of scroll able container is it possible to scroll.

**Comment by IanYates** [comment]
Same behaviour as reported by @sava999 in IE 11 on 8.1 using freshly downloaded code from GitHub.  I'm going to have a look through F12 tools now to see if I can spot anything (unlikely as I've just started looking at this library in the past day or so - nice job! - but it's worth a shot)

**Comment by malihu** [comment]
I'll try creating an example (I'll post the URL here) that'll output some variable/function values in console so you can give me some feedback. The weird thing is that it's working on my Windows phone (8.1) and on Windows simulator (for touch) on Win 8.1 and Win 10 (I don't have a touch-enabled laptop though).

**Comment by IanYates** [comment]
Sounds great - happy to give things a try :)  I've got a Toshiba tablet with Windows 10 / Edge I can try tomorrow (it's 11pm here in Australia at the moment) and a couple of Windows 8.1 machines (Surface Pro 3 & a HP touch laptop).  I'll try things on there and report.  I've found sometimes that if I do manage to touch the scrollbar itself and make it move then, if I use my trackpad to bring the cursor onto the web page it acts as though the moved mouse cursor is my finger all of a sudden.  Then the scrollbar doesn't work very well even when touched directly.  And then it does...  Sorry that's not very precise - I'll try to better correlate when there's some debug output so I can do some very specific reports for you :)

**Comment by malihu** [comment]
OK great. Can you confirm that latest version is working on your tablet?

**Comment by IanYates** [comment]
I've just fetched the latest on the win 10 tablet and tried it in edge.  As far as I can see, the same faulty behaviour is present as what I have in IE 11 on Win 8.1 including the difficult to describe behaviour I mentioned above.

Again it's around 11pm here but I'll check tomorrow morning and throughout the day to see if you've got a version you'd like me to try with some meaningful debug output.

**Comment by malihu** [comment]
OK check this URL: 
http://manos.malihu.gr/repository/tests/test-pointer-events/

Try to tap/click the content (via touch, trackpad etc.) and let me know what the `pointerType` output  is. I'm suspecting that in hybrid devices the returned value might be wrong...

**Comment by IanYates** [comment]
Mousing in there gives
mouse / pointerdown / 1 / undefined

Touching in there gives
touch / pointerdown / 108 / undefined

Is that what you were expecting?

This is IE 11 on Win 8.1

**Comment by malihu** [comment]
I'm also doing some tests myself on VMs. 

These values are correct. So when `touch / pointerdown / 108 / undefined` and touch-swiping content, it doesn't scroll at all?

**Comment by IanYates** [comment]
I've just loaded the page again.
No scrolling at all.

pointerType shows a red "2".

Actually, it's not "no scrolling at all".  If the window is small enough, I can make the entire window scroll from within the little scrolling region, but it's as though I have to scroll a bit with my finger inside of the region before the entire window moves.

I'll take a Camtasia video where, hopefully, my touch points will be visible for you to see.

**Comment by IanYates** [comment]
Link: http://1drv.ms/1RLaPQ1

I found actually that it's not the size of the window, it's actually that the first attempt to scroll inside the region fails, and then the second attempt scrolls the window instead of the region.

I started with some mouse scrolling in the video.  Then I tried touch straight away.  That seemed to move the mouse cursor but I think that might've been an artefact of Camtasia's capturing.

So I refreshed the page and then tried again.  You can see the small touch points in the video.

I don't know how much help that is, but I can capture any console output and include it in the video for you.

**Comment by IanYates** [comment]
Link: http://1drv.ms/1RLaPQ1

I found actually that it's not the size of the window, it's actually that the first attempt to scroll inside the region fails, and then the second attempt scrolls the window instead of the region.

I started with some mouse scrolling in the video.  Then I tried touch straight away.  That seemed to move the mouse cursor but I think that might've been an artefact of Camtasia's capturing.

So I refreshed the page and then tried again.  You can see the small touch points in the video.

I don't know how much help that is, but I can capture any console output and include it in the vide

**Comment by rajasri215** [comment]
@mayklEm : We see that you had faced a issue : "If I touch the section where anchor tag is, scroll the section and release fro the same area where anchor is it will trigger a click event on release". Did you happen to find any solution to overcome this issue.

**Comment by benjithaimmortal** [comment]
FYI, this also isn't working on precision touch pads -- on both modern versions of IE and Edge. Is it based on a scroll event listener? Scrolling on PTPs does not record as a scroll event.
